"""federated forecasts

Revision ID: 3de61cc073d9
Revises: 606bf8bc0a57
Create Date: 2026-09-16 14:11:21.694841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de61cc073d9'
down_revision: Union[str, Sequence[str], None] = '606bf8bc0a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('sku_code', sa.Text(), nullable=False),
    sa.Column('predicted_daily_use', sa.Float(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['sku_code'], ['skus.code'], ),
    sa.PrimaryKeyConstraint('facility_id', 'sku_code')
    )
    op.create_index(op.f('ix_forecasts_computed_at'), 'forecasts', ['computed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_computed_at'), table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
