"""facility phone contacts

Revision ID: 44eac614315b
Revises: 82f5c8076824
Create Date: 2026-09-16 15:29:32.820334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44eac614315b'
down_revision: Union[str, Sequence[str], None] = '82f5c8076824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_contacts',
    sa.Column('phone_hash', sa.Text(), nullable=False),
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('masked', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('reporter', 'supervisor')", name='ck_facility_contacts_role'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('phone_hash')
    )
    op.create_index(op.f('ix_facility_contacts_facility_id'), 'facility_contacts', ['facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_contacts_facility_id'), table_name='facility_contacts')
    op.drop_table('facility_contacts')
    # ### end Alembic commands ###
