"""federation round inspector

Revision ID: 82f5c8076824
Revises: 3de61cc073d9
Create Date: 2026-09-16 15:09:49.647159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82f5c8076824'
down_revision: Union[str, Sequence[str], None] = '3de61cc073d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('federation_rounds', sa.Column('run_id', sa.Text(), nullable=False))
    op.add_column('federation_rounds', sa.Column('strategy', sa.Text(), nullable=True))
    op.add_column('federation_rounds', sa.Column('baseline_mae', sa.Float(), nullable=True))
    op.add_column('federation_rounds', sa.Column('per_silo', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('federation_rounds', sa.Column('silos_reporting', sa.Integer(), nullable=True))
    op.alter_column('federation_rounds', 'global_val_mae',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_federation_rounds_completed_at'), 'federation_rounds', ['completed_at'], unique=False)
    op.create_index(op.f('ix_federation_rounds_run_id'), 'federation_rounds', ['run_id'], unique=False)
    op.create_index('uq_federation_round', 'federation_rounds', ['run_id', 'round_no'], unique=True)
    op.drop_column('federation_rounds', 'per_silo_mae')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('federation_rounds', sa.Column('per_silo_mae', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('uq_federation_round', table_name='federation_rounds')
    op.drop_index(op.f('ix_federation_rounds_run_id'), table_name='federation_rounds')
    op.drop_index(op.f('ix_federation_rounds_completed_at'), table_name='federation_rounds')
    op.alter_column('federation_rounds', 'global_val_mae',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('federation_rounds', 'silos_reporting')
    op.drop_column('federation_rounds', 'per_silo')
    op.drop_column('federation_rounds', 'baseline_mae')
    op.drop_column('federation_rounds', 'strategy')
    op.drop_column('federation_rounds', 'run_id')
    # ### end Alembic commands ###
