"""initial schema

Revision ID: 1ed05281d12d
Revises: 
Create Date: 2026-09-16 00:45:25.566444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ed05281d12d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('state_silo', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('beds_total', sa.Integer(), nullable=False),
    sa.CheckConstraint("type IN ('PHC', 'CHC', 'SUBCENTRE')", name='ck_facilities_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_district'), 'facilities', ['district'], unique=False)
    op.create_index(op.f('ix_facilities_state_silo'), 'facilities', ['state_silo'], unique=False)
    op.create_table('federation_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('global_val_mae', sa.Numeric(), nullable=True),
    sa.Column('per_silo_mae', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bytes_transmitted', sa.BigInteger(), nullable=True),
    sa.Column('tensor_shapes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weights_sha256', sa.Text(), nullable=True),
    sa.Column('raw_rows_transmitted', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stockout_days', sa.Integer(), nullable=True),
    sa.Column('facilities_affected', sa.Integer(), nullable=True),
    sa.Column('transfers_executed', sa.Integer(), nullable=True),
    sa.Column('total_km', sa.Numeric(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to_ref', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('provider_sid', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbreak_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('disease_category', sa.Text(), nullable=True),
    sa.Column('radius_km', sa.Numeric(), nullable=True),
    sa.Column('severity', sa.Numeric(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_matrix_cache',
    sa.Column('origin_id', sa.Text(), nullable=False),
    sa.Column('dest_id', sa.Text(), nullable=False),
    sa.Column('distance_km', sa.Numeric(), nullable=True),
    sa.Column('duration_min', sa.Numeric(), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('origin_id', 'dest_id')
    )
    op.create_table('skus',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('is_controlled', sa.Boolean(), nullable=False),
    sa.Column('cold_chain', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('state_silo', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('facility_id', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'state_officer', 'block_mo', 'facility_user')", name='ck_users_role'),
    sa.CheckConstraint('email = lower(email)', name='ck_users_email_lower'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bed_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('beds_occupied', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_status_facility_id'), 'bed_status', ['facility_id'], unique=False)
    op.create_index(op.f('ix_bed_status_recorded_at'), 'bed_status', ['recorded_at'], unique=False)
    op.create_table('facility_sku_state',
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('sku_code', sa.Text(), nullable=False),
    sa.Column('qty_on_hand', sa.Float(), nullable=False),
    sa.Column('daily_burn_rate', sa.Float(), nullable=False),
    sa.Column('days_of_stock', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_source', sa.Text(), nullable=True),
    sa.Column('last_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['sku_code'], ['skus.code'], ),
    sa.PrimaryKeyConstraint('facility_id', 'sku_code')
    )
    op.create_index('ix_fss_sku_status', 'facility_sku_state', ['sku_code', 'status'], unique=False)
    op.create_index('ix_fss_status', 'facility_sku_state', ['status'], unique=False)
    op.create_table('staff_checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('staff_ref', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_checkins_checked_in_at'), 'staff_checkins', ['checked_in_at'], unique=False)
    op.create_index(op.f('ix_staff_checkins_facility_id'), 'staff_checkins', ['facility_id'], unique=False)
    op.create_table('stock_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('sku_code', sa.Text(), nullable=False),
    sa.Column('qty_on_hand', sa.Numeric(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('footfall_same_day', sa.Integer(), nullable=True),
    sa.Column('reporter_ref', sa.Text(), nullable=True),
    sa.Column('channel_msg_id', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("source IN ('form', 'voice', 'photo', 'sms', 'ivr', 'whatsapp', 'seed', 'transfer')", name='ck_stock_readings_source'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['sku_code'], ['skus.code'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['stock_readings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_msg_id')
    )
    op.create_index('ix_readings_facility_sku_time', 'stock_readings', ['facility_id', 'sku_code', 'reported_at'], unique=False)
    op.create_index(op.f('ix_stock_readings_facility_id'), 'stock_readings', ['facility_id'], unique=False)
    op.create_index(op.f('ix_stock_readings_reported_at'), 'stock_readings', ['reported_at'], unique=False)
    op.create_index(op.f('ix_stock_readings_sku_code'), 'stock_readings', ['sku_code'], unique=False)
    op.create_index(op.f('ix_stock_readings_superseded_by'), 'stock_readings', ['superseded_by'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_facility', sa.Text(), nullable=False),
    sa.Column('to_facility', sa.Text(), nullable=False),
    sa.Column('sku_code', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('route_km', sa.Numeric(), nullable=True),
    sa.Column('eta_hours', sa.Numeric(), nullable=True),
    sa.Column('route_polyline', sa.Text(), nullable=True),
    sa.Column('route_source', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.Text(), nullable=True),
    sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'approved', 'rejected', 'completed')", name='ck_transfers_status'),
    sa.ForeignKeyConstraint(['from_facility'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['sku_code'], ['skus.code'], ),
    sa.ForeignKeyConstraint(['to_facility'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_status'), 'transfers', ['status'], unique=False)
    op.create_table('trust_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('sku_code', sa.Text(), nullable=True),
    sa.Column('z_score', sa.Numeric(), nullable=True),
    sa.Column('rule', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['sku_code'], ['skus.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_flags_facility_id'), 'trust_flags', ['facility_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('actor_ref', sa.Text(), nullable=True),
    sa.Column('actor_role', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_transfer_id'), 'approvals', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_transfer_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_trust_flags_facility_id'), table_name='trust_flags')
    op.drop_table('trust_flags')
    op.drop_index(op.f('ix_transfers_status'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_stock_readings_superseded_by'), table_name='stock_readings')
    op.drop_index(op.f('ix_stock_readings_sku_code'), table_name='stock_readings')
    op.drop_index(op.f('ix_stock_readings_reported_at'), table_name='stock_readings')
    op.drop_index(op.f('ix_stock_readings_facility_id'), table_name='stock_readings')
    op.drop_index('ix_readings_facility_sku_time', table_name='stock_readings')
    op.drop_table('stock_readings')
    op.drop_index(op.f('ix_staff_checkins_facility_id'), table_name='staff_checkins')
    op.drop_index(op.f('ix_staff_checkins_checked_in_at'), table_name='staff_checkins')
    op.drop_table('staff_checkins')
    op.drop_index('ix_fss_status', table_name='facility_sku_state')
    op.drop_index('ix_fss_sku_status', table_name='facility_sku_state')
    op.drop_table('facility_sku_state')
    op.drop_index(op.f('ix_bed_status_recorded_at'), table_name='bed_status')
    op.drop_index(op.f('ix_bed_status_facility_id'), table_name='bed_status')
    op.drop_table('bed_status')
    op.drop_table('users')
    op.drop_table('skus')
    op.drop_table('route_matrix_cache')
    op.drop_table('outbreak_events')
    op.drop_table('outbound_messages')
    op.drop_table('impact_ledger')
    op.drop_table('federation_rounds')
    op.drop_index(op.f('ix_facilities_state_silo'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_district'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
