"""capture and trust layer

Revision ID: 606bf8bc0a57
Revises: c152fdef4bdb
Create Date: 2026-09-16 07:56:34.875873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '606bf8bc0a57'
down_revision: Union[str, Sequence[str], None] = 'c152fdef4bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bed_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('ward', sa.Text(), nullable=False),
    sa.Column('beds_total', sa.Integer(), nullable=True),
    sa.Column('beds_occupied', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('code_expected', sa.Text(), nullable=True),
    sa.Column('code_read', sa.Text(), nullable=True),
    sa.Column('code_ok', sa.Boolean(), nullable=True),
    sa.Column('loc_method', sa.Text(), nullable=True),
    sa.Column('loc_lat', sa.Float(), nullable=True),
    sa.Column('loc_lng', sa.Float(), nullable=True),
    sa.Column('loc_accuracy_m', sa.Float(), nullable=True),
    sa.Column('geofence_km', sa.Float(), nullable=True),
    sa.Column('geofence_ok', sa.Boolean(), nullable=True),
    sa.Column('register_admissions', sa.Integer(), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('media_ref', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification', sa.Text(), nullable=False),
    sa.CheckConstraint("verification IN ('verified', 'unverified', 'rejected')", name='ck_bed_reports_verification'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_reports_facility_id'), 'bed_reports', ['facility_id'], unique=False)
    op.create_index(op.f('ix_bed_reports_reported_at'), 'bed_reports', ['reported_at'], unique=False)
    op.create_table('facility_trust',
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.Text(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("band IN ('good', 'watch', 'audit')", name='ck_facility_trust_band'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_index('ix_facility_trust_score', 'facility_trust', ['score'], unique=False)
    op.create_table('verification_codes',
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('facility_id', 'for_date')
    )
    op.create_table('medicine_movements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Text(), nullable=False),
    sa.Column('sku_code', sa.Text(), nullable=False),
    sa.Column('from_ref', sa.Text(), nullable=False),
    sa.Column('to_facility', sa.Text(), nullable=False),
    sa.Column('state_silo', sa.Text(), nullable=False),
    sa.Column('qty_dispatched', sa.Numeric(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatch_source', sa.Text(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.Column('expected_by', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qty_received', sa.Numeric(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_via', sa.Text(), nullable=True),
    sa.Column('received_by_ref', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("dispatch_source IN ('warehouse', 'transfer', 'seed')", name='ck_movements_dispatch_source'),
    sa.CheckConstraint("status IN ('in_transit', 'received', 'short', 'over', 'cancelled')", name='ck_movements_status'),
    sa.CheckConstraint('qty_dispatched > 0', name='ck_movements_qty_positive'),
    sa.ForeignKeyConstraint(['sku_code'], ['skus.code'], ),
    sa.ForeignKeyConstraint(['to_facility'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_movements_dispatched_at'), 'medicine_movements', ['dispatched_at'], unique=False)
    op.create_index(op.f('ix_medicine_movements_sku_code'), 'medicine_movements', ['sku_code'], unique=False)
    op.create_index(op.f('ix_medicine_movements_state_silo'), 'medicine_movements', ['state_silo'], unique=False)
    op.create_index(op.f('ix_medicine_movements_to_facility'), 'medicine_movements', ['to_facility'], unique=False)
    op.create_index('ix_movements_facility_time', 'medicine_movements', ['to_facility', 'dispatched_at'], unique=False)
    op.create_index('ix_movements_open', 'medicine_movements', ['status', 'expected_by'], unique=False)
    op.create_index('uq_movement_batch', 'medicine_movements', ['batch_id', 'to_facility', 'sku_code'], unique=True)
    op.add_column('staff_checkins', sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('staff_checkins', sa.Column('shift', sa.Text(), nullable=True))
    op.add_column('staff_checkins', sa.Column('source', sa.Text(), nullable=True))
    op.add_column('staff_checkins', sa.Column('cell_id', sa.Text(), nullable=True))
    op.add_column('staff_checkins', sa.Column('loc_method', sa.Text(), nullable=True))
    op.add_column('staff_checkins', sa.Column('geofence_km', sa.Float(), nullable=True))
    op.add_column('staff_checkins', sa.Column('geofence_ok', sa.Boolean(), nullable=True))
    op.add_column('staff_checkins', sa.Column('footfall_same_period', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_checkins', 'footfall_same_period')
    op.drop_column('staff_checkins', 'geofence_ok')
    op.drop_column('staff_checkins', 'geofence_km')
    op.drop_column('staff_checkins', 'loc_method')
    op.drop_column('staff_checkins', 'cell_id')
    op.drop_column('staff_checkins', 'source')
    op.drop_column('staff_checkins', 'shift')
    op.drop_column('staff_checkins', 'checked_out_at')
    op.drop_index('uq_movement_batch', table_name='medicine_movements')
    op.drop_index('ix_movements_open', table_name='medicine_movements')
    op.drop_index('ix_movements_facility_time', table_name='medicine_movements')
    op.drop_index(op.f('ix_medicine_movements_to_facility'), table_name='medicine_movements')
    op.drop_index(op.f('ix_medicine_movements_state_silo'), table_name='medicine_movements')
    op.drop_index(op.f('ix_medicine_movements_sku_code'), table_name='medicine_movements')
    op.drop_index(op.f('ix_medicine_movements_dispatched_at'), table_name='medicine_movements')
    op.drop_table('medicine_movements')
    op.drop_table('verification_codes')
    op.drop_index('ix_facility_trust_score', table_name='facility_trust')
    op.drop_table('facility_trust')
    op.drop_index(op.f('ix_bed_reports_reported_at'), table_name='bed_reports')
    op.drop_index(op.f('ix_bed_reports_facility_id'), table_name='bed_reports')
    op.drop_table('bed_reports')
    # ### end Alembic commands ###
