"""facility briefings cache

One table, and it is a cache rather than a record: every row can be thrown away
and regenerated, and the screen works with the table empty because the
deterministic line needs no cache at all.

Two caps are built into the shape:

  * the composite primary key (facility_id, lang) means one centre can hold at
    most two rows, ever — the button overwrites rather than appends, so a judge
    clicking it fifty times writes the same two rows;
  * `ix_briefings_generated_at` exists so the application can evict the least
    recently generated once `max_briefing_rows` is reached. 3,510 facilities in
    two languages would be roughly 4 MB of cache on a 1 GB volume.

Written by hand rather than autogenerated: the local database was a revision
behind when this was created, and an autogenerated diff would have swept up
that drift along with the table.

Revision ID: f3a81c6d5492
Revises: e4d7a9c31b52
Create Date: 2026-09-22

"""

from alembic import op
import sqlalchemy as sa

revision = "f3a81c6d5492"
down_revision = "e4d7a9c31b52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "facility_briefings",
        sa.Column("facility_id", sa.Text(), nullable=False),
        sa.Column("lang", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        # Fingerprint of the stock position the line describes, so advice
        # expires when that position changes and not only when the clock does.
        sa.Column("inputs_hash", sa.Text(), nullable=False),
        # Which model wrote it. A deterministic row and a generated row are not
        # interchangeable, and the screen labels them differently.
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"], ["facilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("facility_id", "lang"),
        sa.CheckConstraint("lang IN ('en', 'hi')", name="ck_briefings_lang"),
    )
    op.create_index(
        "ix_briefings_generated_at", "facility_briefings", ["generated_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_briefings_generated_at", table_name="facility_briefings")
    op.drop_table("facility_briefings")
