"""outbreak pre-positioning

Revision ID: e498894a7fbc
Revises: 44eac614315b
Create Date: 2026-09-16 15:50:33.416197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e498894a7fbc'
down_revision: Union[str, Sequence[str], None] = '44eac614315b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbreak_demand',
    sa.Column('outbreak_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('sku_code', sa.Text(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['outbreak_id'], ['outbreak_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_code'], ['skus.code'], ),
    sa.PrimaryKeyConstraint('outbreak_id', 'facility_id', 'sku_code')
    )
    op.create_index('ix_outbreak_demand_facility', 'outbreak_demand', ['facility_id', 'expires_at'], unique=False)
    op.add_column('outbreak_events', sa.Column('state_silo', sa.Text(), nullable=True))
    op.add_column('outbreak_events', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('outbreak_events', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('outbreak_events', sa.Column('facilities_affected', sa.Integer(), nullable=True))
    op.add_column('outbreak_events', sa.Column('declared_by', sa.Text(), nullable=True))
    op.add_column('outbreak_events', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('outbreak_events', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbreak_events', sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('outbreak_events', 'radius_km',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('outbreak_events', 'severity',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_outbreak_events_expires_at'), 'outbreak_events', ['expires_at'], unique=False)
    op.create_index(op.f('ix_outbreak_events_state_silo'), 'outbreak_events', ['state_silo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbreak_events_state_silo'), table_name='outbreak_events')
    op.drop_index(op.f('ix_outbreak_events_expires_at'), table_name='outbreak_events')
    op.alter_column('outbreak_events', 'severity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('outbreak_events', 'radius_km',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('outbreak_events', 'cleared_at')
    op.drop_column('outbreak_events', 'expires_at')
    op.drop_column('outbreak_events', 'note')
    op.drop_column('outbreak_events', 'declared_by')
    op.drop_column('outbreak_events', 'facilities_affected')
    op.drop_column('outbreak_events', 'lng')
    op.drop_column('outbreak_events', 'lat')
    op.drop_column('outbreak_events', 'state_silo')
    op.drop_index('ix_outbreak_demand_facility', table_name='outbreak_demand')
    op.drop_table('outbreak_demand')
    # ### end Alembic commands ###
